[global]
   workgroup = WORKGROUP
   server string = LibraryIT Server
   security = user
   map to guest = Bad User
   
   # --- Konfigurasi Log ---
   # Mencatat ke file lokal di container yang nantinya di-share ke logger
   log file = /var/log/samba/libraryit.log
   max log size = 50
   vfs objects = full_audit
   
   # Format log: [LEVEL] [USERNAME] [AKSI] [NAMA FILE/SHARE]
   # %T = Timestamp, %u = Username, %a = Arsitektur (tidak dipakai), %m = Hostname (tidak dipakai)
   # Kita akan memproses mentahannya di service logger agar sesuai format soal
   full_audit:prefix = %u|%I
   full_audit:success = mkdir rename unlink open pwrite connect
   full_audit:failure = connect open
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE

[ebooks]
   path = /libraryit/ebooks
   browseable = yes
   write list = @staff
   valid users = @staff, @readonly

[papers]
   path = /libraryit/papers
   browseable = yes
   write list = @staff
   valid users = @staff, @readonly

[sourcecode]
   path = /libraryit/sourcecode
   browseable = no
   valid users = @staff

[docs]
   path = /libraryit/docs
   browseable = yes
   write list = librarian
   valid users = @staff, @readonly